### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by ararslan** [johnmyleswhite/Calculus.jl#120]
It would be great if someone could tag a new release. There are a lot of deprecation warnings emitted from the current release that have been fixed on master.

**Comment by mlubin** [comment]
@johnmyleswhite, could you grant me admin access? Looks like [attobot](https://github.com/attobot/attobot) isn't set up here.

**Comment by ararslan** [comment]
Would it be worthwhile to put Calculus in an organization such as JuliaMath?

**Comment by ararslan** [comment]
Also, I think you should be able to create a new tag the old fashioned way with PkgDev without needed administrator privileges.

**Comment by mlubin** [comment]
No objection here if JuliaMath is willing to host. I was hoping to avoid `PkgDev.tag()`, that's like digging out the VCR player.

**Comment by mlubin** [comment]
PkgDev didn't even work (https://github.com/JuliaLang/PkgDev.jl/issues/101), but here we go: https://github.com/JuliaLang/METADATA.jl/pull/14370

**Comment by ararslan** [comment]
Thanks!

**Comment by johnmyleswhite** [comment]
It's been so long since I've used GitHub seriously that I've forgotten how to give admin access. But I'm happy to transfer this repo to JuliaMath whenever. Please e-mail me directly to make sure I see the request.
