### ISSUE TITLE
Do you want to mentor Equations.jl for JSoC?

### ISSUE THREAD

**Issue by jhlq** [johnmyleswhite/Calculus.jl#68]
Hello Mr White! This package shares similarities with the [Equations](https://github.com/jhlq/Equations.jl) package and have been helped by you previously, both through blog posts and discussion.

Am therefore wondering if you would like to mentor not only the development of Julia code but also the associated course creation and (developing) developer hiring within the enveloping project hopefully featured in this years JSoC.

As stated in the group: If the project is accepted for JSoC all compensation will be pledged for expanding the project and you will be given power of veto over any suggested expenses.

**Comment by johnmyleswhite** [comment]
The Equations package is a bit far from my goals for the summer, so I'm sorry to decline.

Good luck finding a mentor!
