### ISSUE TITLE
Error with numerical integration

### ISSUE THREAD

**Issue by bcameron43** [johnmyleswhite/Calculus.jl#78]
Obviously, these don't add up correctly.
julia> f(x) = x^3*exp(-x^2/2)/2
f (generic function with 1 method)
julia> integrate(f,0,20)
1.0000000000107998
julia> integrate(f,20,30)
4.30545586095874e-84
julia> integrate(f,0,30)
1.3729357524611979e-9

**Comment by johnmyleswhite** [comment]
Don't use that function. We're going to remove it completely.

Use the `quadgk` function instead.

**Comment by mlubin** [comment]
@johnmyleswhite, time to deprecate it?

**Comment by johnmyleswhite** [comment]
Yes, I'm just overwhelmed at work this week, so I doubt I'll be able to write a PR. But we should completely bail on integration ASAP.

**Comment by bcameron43** [comment]
Thanks
