### ISSUE TITLE
simplify give wrong result

### ISSUE THREAD

**Issue by ZacLN** [johnmyleswhite/Calculus.jl#82]
Hey,
`simplify(:(a-0))` gives `-a` rather than `a`

due to the reinterpretation of `Expr(:call,:-,:a)` following the stripping of zeros

**Comment by mlubin** [comment]
That's unfortunate. Care to fix it with a PR?

**Comment by Zac12345** [comment]
Will do I'm just trying to work out how to do one!

**Comment by mlubin** [comment]
Fixed by https://github.com/johnmyleswhite/Calculus.jl/pull/108
