### ISSUE TITLE
Support for complex numbers

### ISSUE THREAD

**Issue by AlexanderKoshkarov** [johnmyleswhite/Calculus.jl#97]
It would be nice if the package would support the complex numbers. Probably it is difficult to check when the derivative exist, and what path to take on the complex plane to take derivative. However if you will make default derivative path (for example along real axis) it should be good enough (I think) for [DifferentialEquations.jl](https://github.com/JuliaDiffEq/DifferentialEquations.jl) where derivatives are used to calculate Jacobian in implicit ODE integrators. (@ChrisRackauckas is using `finite_difference!` and `finite_difference_jacobian!` in DifferentialEquations.jl)
If it would be possible to indicate the curve on complex plane where to take derivative, it also would be awesome. Thanks.

```
julia> using Calculus; derivative(sin,0.0)
0.9999999999938886
julia> derivative(sin,0.0 + 0im)
ERROR: MethodError: no method matching eps(::Type{Complex{Float64}})
Closest candidates are:
  eps(::Date) at dates/types.jl:231
  eps(::DateTime) at dates/types.jl:230
  eps() at float.jl:499
  ...
 in finite_difference(::Base.#sin, ::Complex{Float64}, ::Symbol) at /home/kosh/.julia/v0.5/Calculus/src/finite_difference.jl:27
 in derivative(::Function, ::Complex{Float64}) at /home/kosh/.julia/v0.5/Calculus/src/derivative.jl:10
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
 in macro expansion at ./REPL.jl:95 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68
```

**Comment by johnmyleswhite** [comment]
This package's finite-differencing functionality isn't going to be developed anymore. At some point in the near-term future I will release [FiniteDiff.jl](https://github.com/johnmyleswhite/FiniteDiff.jl), which replaces that part of this package's functionality. You can open a PR there that provides the functionality you want.
